stages:
  - test
php5.5-phpunit:
  stage: test
  image: interexperts/php-5.5
  script:
    - composer install --no-progress
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpdoc
  artifacts:
    paths:
      - built/